name: weekly-ai-practice
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_4
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.10.19=h981015d_0
  - setuptools=80.9.0=py310haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - black==26.1.0
      - bleach==6.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.2
      - coverage==7.13.1
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.20.3
      - flake8==7.3.0
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fqdn==1.5.1
      - fsspec==2026.1.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - iniconfig==2.3.0
      - ipdb==0.13.13
      - ipykernel==7.1.0
      - ipython==8.38.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - librt==0.7.8
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mccabe==0.7.0
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - mypy==1.19.1
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - notebook==7.5.2
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - onnx==1.20.1
      - onnxruntime==1.23.2
      - opencv-python==4.13.0.90
      - opencv-python-headless==4.13.0.90
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==1.0.3
      - pillow==12.1.0
      - platformdirs==4.5.1
      - plotly==6.5.2
      - pluggy==1.6.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - protobuf==6.33.4
      - psutil==7.2.1
      - pure-eval==0.2.3
      - pycocotools==2.0.11
      - pycodestyle==2.14.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyflakes==3.4.0
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyreadline3==3.5.4
      - pytest==9.0.2
      - pytest-cov==7.0.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - pytokens==0.4.0
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==2.1.0
      - sentry-sdk==2.50.0
      - simsimd==6.5.12
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - stringzilla==4.6.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - timm==1.0.24
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - tomli==2.4.0
      - torch==2.9.1
      - torchaudio==2.9.1
      - torchvision==0.24.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.6
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - wandb==0.24.0
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - werkzeug==3.1.5
      - widgetsnbextension==4.0.15
prefix: C:\Users\manju\.conda\envs\weekly-ai-practice
